# Generated by Django 5.2.5 on 2025-08-25 07:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_applied_date_jobapplicant_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobapplicant',
            unique_together={('job', 'user')},
        ),
    ]
