# Generated by Django 5.2.5 on 2025-08-25 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_jobapplicant_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplicant',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
    ]
